// Code generated by Kitex v0.9.1. DO NOT EDIT.

package userservice

import (
	user_microservice "github.com/AdrianWangs/ai-nexus/go-service/test/kitex_gen/user_microservice"
	server "github.com/cloudwego/kitex/server"
)

// NewInvoker creates a server.Invoker with the given handler and options.
func NewInvoker(handler user_microservice.UserService, opts ...server.Option) server.Invoker {
	var options []server.Option

	options = append(options, opts...)

	s := server.NewInvoker(options...)
	if err := s.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	if err := s.Init(); err != nil {
		panic(err)
	}
	return s
}
