// Code generated by hertz generator.

package user_microservice

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getuserMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _loginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _registerMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _thirdpartyloginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateuserprofileMw() []app.HandlerFunc {
	// your code...
	return nil
}
