services:
#    etcd:
#        image: bitnami/etcd:3.5.14
#        container_name: etcd
#        ports:
#            - "2379:2379"
#            - "2380:2380"
#        environment:
#            - ALLOW_SINGLE_CLUSTER=true
#            - TZ=Asia/Shanghai
#            - ALLOW_NONE_AUTHENTICATION=yes
    nacos:
        image: nacos/nacos-server:v2.3.2
        container_name: nacos
        ports:
            - "8848:8848"
            - "9849:9849"
            - "9849:9849"
        volumes:
            - ./nacos/conf:/home/nacos/conf
            - ./nacos/logs:/home/nacos/logs
            - ./nacos/data:/home/nacos/data
        environment:
            - PREFER_HOST_MODE=hostname
            - MODE=standalone
        networks:
            - micro-service-net
    sentinel:
        image: bladex/sentinel-dashboard:1.8.7
        container_name: sentinel
        ports:
            - "8858:8858"
        networks:
            - micro-service-net
    redis:
        image: redis:6.2.6
        container_name: redis
        ports:
            - "6379:6379"
        volumes:
            - ./redis/data:/data
        networks:
            - micro-service-net
#    mysql:
#        image: mysql:5.7 # 使用MySQL官方镜像，版本8
#        restart: always # 容器退出后总是重启
#        environment:
#            MYSQL_ROOT_PASSWORD: 88888888 # 设置root用户的密码，生产环境中请使用更复杂的密码
#            MYSQL_DATABASE: go-zero-demo # 初始化时创建的数据库名称
#            MYSQL_USER: go-zero # 创建的新用户
#            MYSQL_PASSWORD: 88888888 # 新用户的密码
#        ports:
#            - "3306:3306" # 映射容器的3306端口到主机的3306端口
#        volumes:
#            - dbdata:/var/lib/mysql # 挂载宿主机的目录到容器的MySQL数据目录，用于持久化数据

networks:
    micro-service-net:
        driver: bridge
#volumes:
#    dbdata: