POST localhost:8888/login
Content-Type: application/json

{
    "UsernameOrEmail": "test",
    "Password": "test"
}

###

GET localhost:8888/get_user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MjIyNjY2NTUsIm9yaWdfaWF0IjoxNzIyMjY2NjU1LCJ1c2VySWQiOjF9.Yf_QTR3O1ztwpMPHwWloZgrvYxJsw16xwilxlc4Mb5A