// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	user_microservice "github.com/AdrianWangs/ai-nexus/go-service/user/biz/router/user_microservice"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	user_microservice.Register(r)
}
