// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	nexus_microservice "github.com/AdrianWangs/ai-nexus/go-service/nexus/biz/router/nexus_microservice"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	nexus_microservice.Register(r)
}
