apiVersion: v1
items:
    -   apiVersion: v1
        kind: Service
        metadata:
            name: go-zero-demo-user-api-svc
            namespace: go-zero-demo
        spec:
            ports:
                -   port: 8888
                    protocol: TCP
                    targetPort: 8888
            selector:
                app: go-zero-demo-user-api
            type: ClusterIP
    -   apiVersion: v1
        kind: Service
        metadata:
            name: go-zero-demo-user-rpc-svc
            namespace: go-zero-demo
        spec:
            ports:
                -   port: 8080
                    protocol: TCP
                    targetPort: 8080
            selector:
                app: go-zero-demo-user-rpc
            type: ClusterIP
    -   apiVersion: apps/v1
        kind: Deployment
        metadata:
            labels:
                app: go-zero-demo-user-api
            name: go-zero-demo-user-api
            namespace: go-zero-demo
        spec:
            progressDeadlineSeconds: 600
            replicas: 3
            revisionHistoryLimit: 5
            selector:
                matchLabels:
                    app: go-zero-demo-user-api
            template:
                metadata:
                    labels:
                        app: go-zero-demo-user-api
                spec:
                    containers:
                        -   image: go-zero-demo/user_api_rpc-api:v1
                            imagePullPolicy: IfNotPresent
                            livenessProbe:
                                initialDelaySeconds: 15
                                periodSeconds: 20
                                tcpSocket:
                                    port: 8888
                            name: go-zero-demo-user-api
                            ports:
                                -   containerPort: 8888
                            readinessProbe:
                                failureThreshold: 3
                                initialDelaySeconds: 5
                                periodSeconds: 10
                                successThreshold: 1
                                tcpSocket:
                                    port: 8888
                                timeoutSeconds: 1
                            resources:
                                limits:
                                    cpu: 300m
                                    memory: 100Mi
                                requests:
                                    cpu: 200m
                                    memory: 50Mi
                            terminationMessagePath: /dev/termination-log
                            terminationMessagePolicy: File
                            volumeMounts:
                                -   mountPath: /etc/localtime
                                    name: timezone
                    dnsPolicy: ClusterFirst
                    imagePullSecrets:
                        -   name: docker-login
                    restartPolicy: Always
                    schedulerName: default-scheduler
                    securityContext: { }
                    serviceAccountName: find-endpoints
                    terminationGracePeriodSeconds: 30
                    volumes:
                        -   hostPath:
                                path: /usr/share/zoneinfo/Asia/Shanghai
                                type: ""
                            name: timezone
    -   apiVersion: apps/v1
        kind: Deployment
        metadata:
            labels:
                app: go-zero-demo-user-rpc
            name: go-zero-demo-user-rpc
            namespace: go-zero-demo
        spec:
            progressDeadlineSeconds: 600
            replicas: 3
            revisionHistoryLimit: 5
            selector:
                matchLabels:
                    app: go-zero-demo-user-rpc
            strategy:
                rollingUpdate:
                    maxSurge: 25%
                    maxUnavailable: 25%
                type: RollingUpdate
            template:
                metadata:
                    labels:
                        app: go-zero-demo-user-rpc
                spec:
                    containers:
                        -   image: go-zero-demo/user_api_rpc-rpc:v1
                            imagePullPolicy: IfNotPresent
                            livenessProbe:
                                failureThreshold: 3
                                initialDelaySeconds: 15
                                periodSeconds: 20
                                successThreshold: 1
                                tcpSocket:
                                    port: 8080
                                timeoutSeconds: 1
                            name: go-zero-demo-user-rpc
                            ports:
                                -   containerPort: 8080
                                    protocol: TCP
                            readinessProbe:
                                failureThreshold: 3
                                initialDelaySeconds: 5
                                periodSeconds: 10
                                successThreshold: 1
                                tcpSocket:
                                    port: 8080
                                timeoutSeconds: 1
                            resources:
                                limits:
                                    cpu: 300m
                                    memory: 100Mi
                                requests:
                                    cpu: 200m
                                    memory: 50Mi
                            terminationMessagePath: /dev/termination-log
                            terminationMessagePolicy: File
                            volumeMounts:
                                -   mountPath: /etc/localtime
                                    name: timezone
                    dnsPolicy: ClusterFirst
                    restartPolicy: Always
                    schedulerName: default-scheduler
                    securityContext: { }
                    serviceAccount: find-endpoints
                    serviceAccountName: find-endpoints
                    terminationGracePeriodSeconds: 30
                    volumes:
                        -   hostPath:
                                path: /usr/share/zoneinfo/Asia/Shanghai
                                type: ""
                            name: timezone
    -   apiVersion: autoscaling/v2
        kind: HorizontalPodAutoscaler
        metadata:
            labels:
                app: go-zero-demo-user-api-hpa-c
            name: go-zero-demo-user-api-hpa-c
            namespace: go-zero-demo
        spec:
            maxReplicas: 10
            metrics:
                -   resource:
                        name: cpu
                        target:
                            averageUtilization: 80
                            type: Utilization
                    type: Resource
            minReplicas: 3
            scaleTargetRef:
                apiVersion: apps/v1
                kind: Deployment
                name: go-zero-demo-user-api
    -   apiVersion: autoscaling/v2
        kind: HorizontalPodAutoscaler
        metadata:
            labels:
                app: go-zero-demo-user-api-hpa-m
            name: go-zero-demo-user-api-hpa-m
            namespace: go-zero-demo
        spec:
            maxReplicas: 10
            metrics:
                -   resource:
                        name: memory
                        target:
                            averageUtilization: 80
                            type: Utilization
                    type: Resource
            minReplicas: 3
            scaleTargetRef:
                apiVersion: apps/v1
                kind: Deployment
                name: go-zero-demo-user-api
    -   apiVersion: autoscaling/v2
        kind: HorizontalPodAutoscaler
        metadata:
            labels:
                app: go-zero-demo-user-rpc-hpa-c
            name: go-zero-demo-user-rpc-hpa-c
            namespace: go-zero-demo
        spec:
            maxReplicas: 10
            metrics:
                -   resource:
                        name: cpu
                        target:
                            averageUtilization: 80
                            type: Utilization
                    type: Resource
            minReplicas: 3
            scaleTargetRef:
                apiVersion: apps/v1
                kind: Deployment
                name: go-zero-demo-user-rpc
    -   apiVersion: autoscaling/v2
        kind: HorizontalPodAutoscaler
        metadata:
            labels:
                app: go-zero-demo-user-rpc-hpa-m
            name: go-zero-demo-user-rpc-hpa-m
            namespace: go-zero-demo
        spec:
            maxReplicas: 10
            metrics:
                -   resource:
                        name: memory
                        target:
                            averageUtilization: 80
                            type: Utilization
                    type: Resource
            minReplicas: 3
            scaleTargetRef:
                apiVersion: apps/v1
                kind: Deployment
                name: go-zero-demo-user-rpc

kind: List
